language: c
before_install:
- sudo apt-get update
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- sudo apt-get install gdal-bin libproj-dev libgdal-dev
- sudo apt-get install r-cran-rjava
- export PATH="$HOME/pandoc:$PATH"
- mkdir $HOME/pandoc
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version
- travis_retry gem install jekyll mime-types
- "./travis-tool.sh r_binary_install rjsonio knitr png testthat"
- "./travis-tool.sh r_install        lubridate pryr nycflights13 microbenchmark stringi babynames stringr ggplot2 ggvis httr tidyr rgdal sp rgeos maptools ggmap classInt RColorBrewer NLP openNLP dplyr"
- "./travis-tool.sh github_package   rstudio/rmarkdown hadley/bookdown hadley/devtools lmullen/gender-data-pkg ropensci/historydata lmullen/mullenMisc"
- mkdir ~/.R
- cp Makevars ~/.R
script: jekyll build
after_success:
- cp -r figures/ _site/figures
deploy:
  provider: s3
  access_key_id: AKIAI3ZE4DKSC6ID3RMA
  secret_access_key:
    secure: Wk625mSLIvtidg9bv4/1rW2Yu6PYJg2I+1VZ11uAPYt4z/B7Vtr0bby8m8SITZtyd6S1UDSBnwoKIuoBET/Ox3NZSl+OeOa0eDXRhL4djkjv2HjwWSMDYV3rzYyIjlOAC58oY9RiAi50W8r1eyfmxPC1NDXAOYSp+7bTOCR8Na4=
  bucket: dh-r.lincolnmullen.com
  endpoint: dh-r.lincolnmullen.com.s3-website-us-east-1.amazonaws.com
  local-dir: _site
  skip_cleanup: true
notifications:
  email:
    on_success: always
    on_failure: always
