language: r
before_install:
  # - sudo apt-get remove -y libgdal1
  # - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  # - sudo apt-get update -y
  - mkdir -p $HOME/R/local
  - curl -O http://datacube.wu.ac.at/src/contrib/openNLPmodels.en_1.5-1.tar.gz
  - tar -C $HOME/R/local -xvf openNLPmodels.en_1.5-1.tar.gz
  - sudo add-apt-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
apt_packages:
  # - libgdal-dev
  # - libproj-dev
  - r-cran-rgdal
r_packages:
  - packrat
script: 
  - make packrat
  - make all
deploy:
  provider: s3
  access_key_id: AKIAI3ZE4DKSC6ID3RMA
  secret_access_key:
    secure: Wk625mSLIvtidg9bv4/1rW2Yu6PYJg2I+1VZ11uAPYt4z/B7Vtr0bby8m8SITZtyd6S1UDSBnwoKIuoBET/Ox3NZSl+OeOa0eDXRhL4djkjv2HjwWSMDYV3rzYyIjlOAC58oY9RiAi50W8r1eyfmxPC1NDXAOYSp+7bTOCR8Na4=
  bucket: dh-r.lincolnmullen.com
  endpoint: dh-r.lincolnmullen.com.s3-website-us-east-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: always
